version: '3.8'

services:
  api-gateway:
    build: 
      context: ../../apps/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pillpal
      - REDIS_URL=redis://redis:6379
      - ENGINE_URL=http://engine-java:8080
      - LLM_REASONER_URL=http://llm-reasoner:3001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  llm-reasoner:
    build:
      context: ../../apps/llm-reasoner
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy

  engine-java:
    build:
      context: ../../apps/engine-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  # Extend from base compose file
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  redis:
    extends:
      file: docker-compose.yml
      service: redis
